---
- name: install Windows Updates
  hosts: windows
  gather_facts: true

  tasks:
    - name: check for missing updates.
      win_updates:
        state: searched
      register: update_count

    - debug:
        var: update_count
