---
- name: Apache server installed
  hosts: apache
  vars:
    iis_test_message: "Hello World!  My test Apache Server"
  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest

  - name: deploy index.html
    template:
      src: index.html.j2
      dest: /var/www/html/index.html

  - name: copy images
    copy:
      src: bird.jpg
      dest: /var/www/html/bird.jpg

  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest

  - name: firewalld enabled and running
    service:
      name: firewalld
      enabled: true
      state: started

  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started

  - name: proper response from apache is received
    uri:
      url: http://{{ ansible_host }}/
      return_content: yes
      validate_certs: no
    register: response
    until: iis_test_message in response.content
    retries: 10
    delay: 1
    ignore_errors: yes

  - name: output url
    debug:
      msg: 'application is available at http://{{ ansible_host }}/'
    when: response is success
