---
- name: Apache server installed
  hosts: apache
  vars:
    iis_test_message: "Hello World!  My test Apache Server"
  tasks:
  - name: Install Web Server
    yum:
      name: httpd
      state: latest

  - name: Create site directory structure
    file:
    path: /src/www
    state: directory
    
  - name: Create main page
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
  
  - name: Activate website
    service:
      name: httpd
      enabled: true
      state: started
      
  - name: install firewall
    yum:
      name: firewalld
      state: latest

  - name: ensure firewall enabled and running
    service:
      name: firewalld
      enabled: true
      state: started

  - name: Open port for site on the firewall
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

  - name: Verify website is running
    uri:
      url: http://{{ ansible_host }}/
      return_content: yes
      validate_certs: no
    register: response
    until: iis_test_message in response.content
    retries: 10
    delay: 1
    ignore_errors: yes

  - name: Website is ready
    debug:
      msg: 'application is available at http://{{ ansible_host }}/'
    when: response is success
