---
- name: Install Windows Updates
  hosts: windows
  gather_facts: false

  tasks:
    - name: Installing only security updates
      win_updates:
        state: searched
        category_names:
          - SecurityUpdates
      register: update_count
      
    - debug:
      var: update_count
